### ISSUE TITLE
missing file in Cha_Bell_WCD2024_initialization.ipynb notebook

### ISSUE THREAD

**Issue by gitleviglenn** [mmbell/Scythe.jl#5]
One of the cells in the Cha_Bell_WCD2024_initialization.ipynb notebook contains this code: `include("scythe_func.jl")`.    However, 'scythe_func.jl' does not appear to be in the repository.

**Comment by mmbell** [comment]
The notebook has been updated to remove that dependency in the v1.0.1 release.
